version: '3'

volumes:
  pg-data:

services:

  server:
    depends_on:
      - postgres
    container_name: server-test
    image: mshev/calendar-server:4
    ports:
      - "50051:50051"

  postgres:
    container_name: postgres-test
    image: mshev/calendar-db:1
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  scaner:
    depends_on:
      - postgres
      - queue
    container_name: scaner-test
    image: mshev/calendar-scaner:4

  notify:
    depends_on:
      - queue
    container_name: notify-test
    image: mshev/calendar-notify:6

  queue:
    container_name: rabbit-test
    image: rabbitmq:3.7.17-management
    ports:
      - "5673:5672"
      - "15673:15672"

  integration_test:
    container_name: test
    image: mshev/calendar-test:3
    depends_on:
      - queue
      - server